canton {
  parameters {
    non-standard-config = yes
  }

  sequencers {
    did-sequencer {
      storage.type = memory
      public-api {
        address = "0.0.0.0"
        port = 6858
      }
      admin-api {
        address = "0.0.0.0"
        port = 6859
      }
      sequencer.type = BFT
    }
  }

  mediators {
    did-mediator {
      admin-api {
        address = "0.0.0.0"
        port = 6860
      }
    }
  }

  participants {
    did-participant {
      storage.type = memory
      ledger-api {
        address = "0.0.0.0"
        port = 6865
      }
      admin-api {
        address = "0.0.0.0"
        port = 6866
      }
      http-ledger-api {
        address = "0.0.0.0"
        port = 7575
      }
    }
  }
}
